name: release

on:
  push:
    branches:
      - main
    tags:
      - v2.*

jobs:
  lint:
    uses: ./.github/workflows/main.yml

  publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: install the dependencies
        run: npm ci
      - name: publish to NPM registry
        run: npm publish
